import { Component, OnDestroy, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';

@Component({
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit, OnDestroy {

  data: LoginModel = {
    email: '',
    password: '',
    isRemember: true
  };

  constructor() { }

  ngOnInit(): void {
    document.body.className = 'bg-gradient-primary';
  }

  ngOnDestroy(): void {
    document.body.className = '';
  }

  doSubmit(form: NgForm) {
    if (form.valid) {
      console.log('送出表單', this.data);
    }
  }

}

// Generated by https://quicktype.io

export interface LoginModel {
  email:      string;
  password:   string;
  isRemember: boolean;
}
